---
# Ansible Collections for K3s/Kubernetes Deployment
# Install with: ansible-galaxy collection install -r requirements.yml

collections:
  # Kubernetes core modules for cluster management
  - name: kubernetes.core
    version: ">=3.0.0"
  
  # Community general utilities and modules
  - name: community.general
    version: ">=8.0.0"
  
  # POSIX utilities for system management
  - name: ansible.posix
    version: ">=1.5.0"
  
  # Built-in modules (explicitly specify for clarity)
  - name: ansible.builtin
    version: ">=2.16.0"
  
  # Docker collection for container management
  - name: community.docker
    version: ">=3.4.0"

# Note: This minimal setup uses custom playbooks instead of external roles
# for better control and reduced dependencies
