---
# Ansible Collections and Roles for K3s/Kubernetes Deployment

# Collections (install with: ansible-galaxy collection install -r requirements.yml)
collections:
  # Kubernetes core modules for cluster management
  - name: kubernetes.core
    version: ">=2.4.0"
  
  # Community general utilities
  - name: community.general
    version: ">=7.0.0"

# Roles (if you want to use external roles instead of your custom playbooks)
# Install with: ansible-galaxy role install -r requirements.yml
# roles:
#   # System configuration roles 
#   - src: geerlingguy.firewall
#     version: 2.4.3


#   - name: geerlingguy.ntp
#     version: 2.7.0

# Note: K3s installation is handled by your custom playbook using the official install script
# No need for kubernetes, docker, or calico roles since K3s bundles everything
